require 'rake'
require 'dotenv'
require 'rspec/core/rake_task'
require './app'

RSpec::Core::RakeTask.new(:spec) do |t|
  t.pattern = Dir.glob('spec/*_spec.rb')
end

task :run do
  Dotenv.load
  App.run!
end

task :default => :spec
